projects:
  ribbon:
    schemaPath: src/graphql/schema.json
    includes:
      - src/graphql/**/*.js
    excludes:
      - ./amplify/**
    extensions:
      amplify:
        codeGenTarget: javascript
        generatedFileName: ''
        docsFilePath: src/graphql
        graphQLApiId: nwmvloum5jc35bwljzgvmvwn3q
      endpoints:
        prod: >-
          https://qlwfvk2gfrfq5p3tdj3t4zvlyq.appsync-api.eu-west-1.amazonaws.com/graphql
