// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "eu-west-1",
    "aws_cognito_identity_pool_id": "eu-west-1:7b9d1d63-e8fd-4a54-a7f3-eed43b37518a",
    "aws_cognito_region": "eu-west-1",
    "aws_user_pools_id": "eu-west-1_z7WYM7RJC",
    "aws_user_pools_web_client_id": "7ovq1kburkeig01kf2tec1ic2r",
    "aws_content_delivery_bucket": "dapp-20190409153519-hostingbucket",
    "aws_content_delivery_bucket_region": "eu-west-1",
    "aws_content_delivery_url": "http://dapp-20190409153519-hostingbucket.s3-website-eu-west-1.amazonaws.com"
};


export default awsmobile;
