// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "eu-west-1",
    "aws_cognito_identity_pool_id": "eu-west-1:c8153bac-a6a4-413c-96d6-90931aee1057",
    "aws_cognito_region": "eu-west-1",
    "aws_user_pools_id": "eu-west-1_XqnjPdmCS",
    "aws_user_pools_web_client_id": "5dc3gd0iqit604a5dnqt48hom6"
};


export default awsmobile;
