// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "eu-west-1",
    "aws_appsync_graphqlEndpoint": "https://wmv62yi2ubhq5d5iavhrj5gjfq.appsync-api.eu-west-1.amazonaws.com/graphql",
    "aws_appsync_region": "eu-west-1",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-ncyya5tejvbwhmcuvl7q6bapoa",
    "aws_cognito_identity_pool_id": "eu-west-1:dda9bbac-2f42-4359-a6c1-34558dae5ddc",
    "aws_cognito_region": "eu-west-1",
    "aws_user_pools_id": "eu-west-1_QsMgMmQk6",
    "aws_user_pools_web_client_id": "3c76eb9jov2qscgo5eh7bnm1b6",
    "aws_content_delivery_bucket": "dapp-20190513133919-hostingbucket",
    "aws_content_delivery_bucket_region": "eu-west-1",
    "aws_content_delivery_url": "http://dapp-20190513133919-hostingbucket.s3-website-eu-west-1.amazonaws.com"
};


export default awsmobile;
